config/routes.rb
Musikpage::Application.routes.draw do
  
  resources :tracks


  get 'signup', to: 'users#new', as: 'signup'
  get 'login', to: 'sessions#new', as: 'login'
  get 'logout', to: 'sessions#destroy', as: 'logout'
 


  resources :sessions


  resources :albums do
    resources :genres
    resources :tracks
    resources :album_steps
end 
	resources :artists


    resources :genres
  resources :users
  root to: 'albums#index'
end

app/models/track.rb
class Track < ActiveRecord::Base
  attr_accessible :album_id, :id, :name
  belongs_to :album

end

app/controllers/tracks_controller.rb
class TracksController < ApplicationController
  # GET /tracks
  # GET /tracks.json
  def index
    @tracks = Track.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @tracks }
    end
  end

  # GET /tracks/1
  # GET /tracks/1.json
  def show
    @track = Track.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @track }
    end
  end

  # GET /tracks/new
  # GET /tracks/new.json
  def new
    @track = Track.new
    # # album = Album.find(params[:album_id])
    # # @track = album.track.create
    # # new_track_form = render_to_string :layout => false
    # # new_track_form.gsub!("[#{@track.id}]", "[#{Time.now.to_i}]")
    # # render :text => new_track_form, :layout => false
    # respond_to do |format|
    #   format.html # new.html.erb
    #   format.json { render json: @track }
    # end
  end

  # GET /tracks/1/edit
  def edit
    @track = Track.find(params[:id])
  end

  # POST /tracks
  # POST /tracks.json
  def create
    @track = Track.new(params[:track])
    @track.album = Album.find(params[:album_id])

    if @track.save
      respond_to do |format|
        format.html {redirect_to :back, notice: "Track eingefuegt." }
        format.js
      end
    end
  end

  # PUT /tracks/1
  # PUT /tracks/1.json
  def update
    @track = Track.find(params[:id])

    respond_to do |format|
      if @track.update_attributes(params[:track])
        format.html { redirect_to @track, notice: 'Track was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @track.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /tracks/1
  # DELETE /tracks/1.json
  def destroy
    @track = Track.find(params[:id])
    @track.destroy
    #album = Album.find(params[:album_id])
  #   unless album.track.exists?(params[:id])
  #     render :text => { :success => false, :msg => 'the track was not found.' }.to_json and return
  #   end
  #   if album.track.destroy(params[:id]) // Rails < 2.3.5, if album.track.destroy(Track.find(params[:id]))
  # render :text => { :success => true }.to_json
  #   else
  #     render :text => { :success => false, :msg => 'something unexpected happened.' }.to_json
  #   end
      respond_to do |format|
      format.html { redirect_to tracks_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/tracks_helper.rb
module TracksHelper
end

app/views/tracks/_form.html.erb
<%= form_for(@track, url: album_tracks_path, remote: true) do |f| %>
  <% if @track.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@track.errors.count, "error") %> prohibited this track from being saved:</h2>

      <ul>
      <% @track.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <h2>new Track</h2>
    <%= f.text_field :name %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/tracks/edit.html.erb
<h1>Editing track</h1>

<%= render 'form' %>

<%= link_to 'Show', @track %> |
<%= link_to 'Back', tracks_path %>

app/views/tracks/index.html.erb
<h1>Listing tracks</h1>

<table>
  <tr>
    <th>Id</th>
    <th>Name</th>
    <th>Album</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @tracks.each do |track| %>
  <tr>
    <td><%= track.id %></td>
    <td><%= track.name %></td>
    <td><%= track.album_id %></td>
    <td><%= link_to 'Show', track %></td>
    <td><%= link_to 'Edit', edit_track_path(track) %></td>
    <td><%= link_to 'Destroy', track, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Track', new_track_path %>

app/views/tracks/new.html.erb
<h1>New track</h1>
<% fields_for 'album[track_attributes][]', @track do |track_form| %>
 <%= render :partial => '/track/form', :locals => { :f => track_form, :track => @track } %>
<% end %>
<%= link_to 'Back', tracks_path %>

app/views/tracks/new.js.erb
$("#link_track").hide().after("<%= j render('form') %>");

app/views/tracks/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Id:</b>
  <%= @track.id %>
</p>

<p>
  <b>Name:</b>
  <%= @track.name %>
</p>

<p>
  <b>Album:</b>
  <%= @track.album_id %>
</p>


<%= link_to 'Edit', edit_track_path(@track) %> |
<%= link_to 'Back', tracks_path %>