config/routes.rb
Musikpage::Application.routes.draw do
  
  resources :tracks


  get 'signup', to: 'users#new', as: 'signup'
  get 'login', to: 'sessions#new', as: 'login'
  get 'logout', to: 'sessions#destroy', as: 'logout'
 


  resources :sessions


  resources :albums do
    resources :genres
    resources :tracks
    resources :album_steps
end 
	resources :artists


    resources :genres
  resources :users
  root to: 'albums#index'
end

app/models/album.rb
class Album < ActiveRecord::Base
  attr_accessible :artist_id, :genre_id, :id, :name, :cover, :user_id

  belongs_to :user
  belongs_to :artist 
  belongs_to :genre
  has_many :tracks

end

app/controllers/albums_controller.rb
class AlbumsController < ApplicationController
before_filter :authorize, only: [:edit, :update, :new]
  def index
    @covers = Album.where("cover != 'NULL'", :order => "RANDOM()")
    @albums = Album.all(:order => "RANDOM()")
    @artists =Artist.all
    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @albums }
      format.js
    end
  end

  def show
    @album = Album.find(params[:id])
    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @album }
    end
  end

  def new
    @album = Album.new
    @artists = Artist.all
    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @album }
    end
  end

  def edit
    @album = Album.find(params[:id])
  end

  def create
    @album = Album.new(params[:album])

      if @album.save
         redirect_to album_album_steps_path(@album)
      else
        format.html { render action: "new" }
        format.json { render json: @album.errors, status: :unprocessable_entity }
    end
  end

  def update
    @album = Album.find(params[:id])

    respond_to do |format|
      if @album.update_attributes(params[:album])
        format.html { redirect_to @album, notice: 'Album was successfully updated.' }
        format.json { head :no_content }
        format.js
      else
        format.html { render action: "edit" }
        format.json { render json: @album.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @album = Album.find(params[:id])
    @album.destroy

    respond_to do |format|
      format.html { redirect_to albums_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/albums_helper.rb
module AlbumsHelper


end

app/views/albums/_form.html.erb
<%= form_for(@album) do |f| %>
  <% if @album.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@album.errors.count, "error") %> prohibited this album from being saved:</h2>

      <ul>
      <% @album.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <h2><%= f.label :artist_id %></h2>
    <%= f.collection_select( :artist_id , @artists, :id, :name )%>
  </div> 
  <div class="field"> 
    <%= f.hidden_field(:user_id, :value => session[:user_id]) %>
 
<%= link_to_submit image_tag("guitar.gif",  :size => "100x50") %>
<% end %>

app/views/albums/_index.html.erb
<h2><%= link_to 'New Album', new_album_path %></h2>
<table>
  <tr>
    <th>Name</th>
    <th>Artist</th>
    <th>Genre</th>
    <th>Image</th>
    <!-- <th></th> -->
  </tr>

<% @albums.each do |album| %>
  <tr>
    <td><%= album.name %></td>
    <% if album.genre_id.blank? %><td></td>
    <% else %>
    <td><%= Artist.find(album.artist_id).name %></td>
    <% end %>
    <% if album.genre_id.blank? %><td></td>
    <% else %>
    <td><%# album.genre_id%><%= Genre.find(album.genre_id).name %></td>    
    <% end %>    
    <% if album.cover.blank? %><td></td>
    <% else %>
    <td><%= image_tag("#{album.cover}", :size => "30x30") %></td>    
    <% end %>
    <!-- <td><%# link_to 'Destroy', album, method: :delete, data: { confirm: 'Are you sure?' } %></td>  -->
  </tr>
<% end %>
</table>

<br />

app/views/albums/add_artist.html.erb
<% content_for :punchline do -%>
<div style="color:white;"><h1>New album</h1>
 Select an Artist or click new Artist</div>
<% end %>


<%= render layout: 'form' do |f| %>

  <div class="field">
    <%= f.label :artist_id %><br />
    <%= f.collection_select( :artist_id , @artists, :id, :name )%>
  </div>    

<% end %>

<%= link_to "new Artist", new_artists_path %>
<%= link_to image_tag("back-arrow.png", :size => "40x40"), :back %>

app/views/albums/edit.html.erb
<h1>Editing album</h1>

<%= render 'form' %>

<%= link_to 'Show', @album %> |
<%= link_to 'Back', albums_path %>

app/views/albums/index.html.erb
<div id="slider">
<ul>
<% @covers.each do |ci| %>
<li><table><td>
    <%= image_tag("#{ci.cover}", :size => "200x200") %>
</td><td>
    <h1><%= ci.name %></h1><br />

        <h2><%= ci.artist.name %></h2><br />
        <% ci.tracks.each do |tr| %>
        <%= tr.name %> <br />
        <% end %>
</td></table>
    </li>
<% end %>
</ul>
</div>
<div id="left"> goLeft </div>
<div id="right"> goRight </div>
<ul id="numbers"> 
<li></li>
</ul>
<br /><div class="divider">&nbsp;</div>
<% unless session[:user_id].blank? %>
<%= render 'index' %>
<% end %>

app/views/albums/new.html.erb
<% content_for :punchline do -%>
<div style="color:white;"><h1>New album</h1>
 Select an Artist or click new Artist </div>
<% end %>


<%= form_for(@album) do |f| %>
  <% if @album.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@album.errors.count, "error") %> prohibited this album from being saved:</h2>

      <ul>
      <% @album.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <h2><%= f.label :artist_id %></h2>
    <%= f.collection_select( :artist_id , @artists, :id, :name )%>
    <%= link_to "new Artist", new_artist_path %>
  </div> 
  <div class="field"> 
    <%= f.hidden_field(:user_id, :value => session[:user_id]) %>
 </div>
<%= link_to_submit image_tag("guitar.gif",  :size => "100x50") %>
<% end %>
<%= link_to image_tag("back-arrow.png", :size => "40x40"), :back %>

app/views/albums/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Id:</b>
  <%= @album.id %>
</p>

<p>
  <b>Name:</b>
  <%= @album.name %>
</p>

<p>
  <b>Artist:</b>
  <%= @album.artist_id %>
</p>

<p>
  <b>Genre:</b>
  <%= @album.genre_id %>
</p>


<%= link_to 'Edit', edit_album_path(@album) %> |
<%= link_to 'Back', albums_path %>